Added use case where a second part on an image forces a cloned Encounter
WildMeOrg/Wildbook pull request #434
Opened 2024-03-29 21:12 UTC by holmbergius

Additional logic to ensure that if you draw a part on top of an image that already has another part then the new part is forced onto a separate encounter. This primarily addresses the use case of many finned species in which we only allow drawing fin parts, such that every additional part is the fin of another individual.

2024-04-01 21:01 UTC, TanyaStere42 commented
use case accepted: people need ability to edit and correct data. Original design was intended to account for possibility of multiple parts being assigned to a single encounter, but that use case has not come up in ~3 years since design decision was made

2024-04-01 21:06 UTC, naknomum commented on src/main/webapp/encounters/manualAnnotation.jsp
> +		if(annots.size()==1){
i think this conditional could be dropped, since it is already tested as part of the `&&` test in line 303.

2024-04-01 21:09 UTC, naknomum requested changes
one change to drop an unnecessary/unneeded `if`

2024-04-01 21:31 UTC, Paul-Kalil commented
Just weighing in on this to see if I understand it correctly. We have two species in ACW and one (so far) in Whiskerbook where individual encounters can have multiple parts, tails for wild dogs and faces for lions and cougars.  Does this change have any impact on those?  Thanks, Paul

2024-04-01 21:45 UTC, TanyaStere42 commented
> Just weighing in on this to see if I understand it correctly. We have two species in ACW and one (so far) in Whiskerbook where individual encounters can have multiple parts, tails for wild dogs and faces for lions and cougars. Does this change have any impact on those? Thanks, Paul

Yes, this will impact manual annotations for all species that have parts associated with them.

2024-04-23 21:50 UTC, holmbergius reviewed
Changed in subsequent commit

2024-04-23 22:28 UTC, holmbergius commented
Qa by @goddesswarship passed as well.

2024-04-24 03:32 UTC, naknomum approved these changes
looks to be making the modification as described

2024-04-24 03:33 UTC, merged