Update index.jsp
WildMeOrg/Wildbook pull request #449
Opened 2024-04-04 22:29 UTC by Paul-Kalil

Replace wild dog profile image with wolf profile image

![WNWB_wolf_lowres](https://github.com/WildMeOrg/Wildbook/assets/88167447/e3f06328-0876-48b4-b3bb-e2b8a5c8c489)

2024-04-05 17:06 UTC, naknomum commented on src/main/webapp/index.jsp
> +	                                <img src="images/WNWB_wolf_lowres.png" alt="" width="85px" height="75px" class="pull-left" />
think this `WNWB_wolf_lowres.png` image also needs to be added to this PR as well.

2024-04-05 17:07 UTC, naknomum requested changes
just a missing image needed, i believe.

2024-04-05 18:52 UTC, Paul-Kalil commented
Thanks

Please go ahead.

Paul

On Fri, Apr 5, 2024, 13:06 Jon Van Oast ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/main/webapp/index.jsp
> <https://github.com/WildMeOrg/Wildbook/pull/449#discussion_r1554013423>:
>
> > @@ -286,7 +286,7 @@ h2.vidcap {
>  	                           Encounter thisEnc=latestIndividuals.get(i);
>  	                           %>
>  	                            <li>
> -	                                <img src="images/wild_dog_logo_2.png" alt="" width="85px" height="75px" class="pull-left" />
> +	                                <img src="images/WNWB_wolf_lowres.png" alt="" width="85px" height="75px" class="pull-left" />
>
> think this WNWB_wolf_lowres.png image also needs to be added to this PR
> as well.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WildMeOrg/Wildbook/pull/449#pullrequestreview-1983736775>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVAVIF3QWP2XNHJDUH5VHDLY33KZXAVCNFSM6AAAAABFYDFO72VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSOBTG4ZTMNZXGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-04-05 19:10 UTC, naknomum commented
> Hi Jon I thought I had attached it, apologies. Here it is again. Thanks Paul

oh i think its just a misunderstanding. the file itself needs to be added to your `patch-18` branch, underneath the `src/main/webapp/images/` directory.  then do some git commands to include it, something like:

```
git add src/main/webapp/images/WNWB_wolf_lowres.png
git commit -m 'new logo added' src/main/webapp/images/WNWB_wolf_lowres.png
git push
```
hopefully i have that about right. then the new file should show up here on this PR, in addition to the change you made to `index.jsp`.

2024-04-09 00:41 UTC, naknomum commented
@Paul-Kalil - did another PR or `master` leak into this? it went from the one file (`index.jsp`) being changed to having these others: `RowFeedback.java`, `dependabot.yml`, and so on.

i am just a little confused as to what might have happened here. :thinking:

2024-04-09 00:57 UTC, Paul-Kalil commented
Hi Jon

I synced with the Master and all these updates came across.

Can we just ignore them?  And did I succeed in getting the new image
uploaded to Patch-18?

I had trouble with the Command Line approach so ended up getting the GitHub
desktop app.

Thanks

Paul

On Mon, Apr 8, 2024 at 5:41 PM Jon Van Oast ***@***.***>
wrote:

> @Paul-Kalil <https://github.com/Paul-Kalil> - did another PR or master
> leak into this? it went from the one file (index.jsp) being changed to
> having these others: RowFeedback.java, dependabot.yml, and so on.
>
> i am just a little confused as to what might have happened here. 🤔
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WildMeOrg/Wildbook/pull/449#issuecomment-2043938471>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVAVIFYP3OUYL6HP7LOPBGTY4M2LRAVCNFSM6AAAAABFYDFO72VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBTHEZTQNBXGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-09 21:34 UTC, naknomum commented
> Hi Jon I synced with the Master and all these updates came across. Can we just ignore them? And did I succeed in getting the new image uploaded to Patch-18? I had trouble with the Command Line approach so ended up getting the GitHub desktop app. Thanks Paul

yeah i have seen where this can happen - git command line and gui tools can get quite complicated with multiple branches, especially since master is getting worked on so frequently. to be honest, i think _undoing_ this might be trickier than starting fresh with a new PR directly from (github's) `wildnorth` branch. this will give us a simpler merge path for `wildnorth`, i think. (then the master changes can come in after.)

i can do that really quickly, since you _did_ get the image and change to index.jsp in here completely now. i will leave a comment here when that is up, so you can review it and make sure i didnt miss your changes.

2024-04-09 21:44 UTC, naknomum commented
@Paul-Kalil please take a look at [PR456](https://github.com/WildMeOrg/Wildbook/pull/456). i think this has just the 2 modifications you made. if that looks good we can get that into `wildnorth` first, then bringing over changes from master can follow.

2024-04-09 23:42 UTC, naknomum commented
closing this as it was superceded by [PR456](https://github.com/WildMeOrg/Wildbook/pull/456).

2024-04-09 23:42 UTC, closed without merging