Enabled users to view public encounter metadata
WildMeOrg/Wildbook pull request #600
Opened 2024-06-10 18:15 UTC by Veda-Gogineni

[Plain-text summary description of the solution]

PR fixes #[REPLACE WITH ISSUE NUMBER]

**Changes**
- [bullet list include any model updates]
- [new or edited functions]
- [significant changes to UX]
- [design decisions, especially if architectural patterns are new/altered]
- [can use text, screenshots, or files]
- [a callout of any ##TODO or ##FIXMEs found/created as part of the fix]

2024-06-10 20:41 UTC, TanyaStere42 commented
@Veda-Gogineni Can you update your PR description? I need the description, reference number, and a brief overview of changes made (see template)

2024-06-10 21:16 UTC, Veda-Gogineni commented
Sure, I will update PR description.

2024-06-11 01:01 UTC, naknomum commented on src/main/webapp/encounters/encounter.jsp
> -            boolean isPublic = ServletUtilities.isEncounterOwnedByPublic(enc) && request.getUserPrincipal() != null; //should at least be logged in
reading through this file, i think we actually need 2 value: one for something is _publicly displayable_ and one when something is _public and can be edited_. perhaps like this:
```
boolean isPublicViewable = ServletUtilities.isEncounterOwnedByPublic(enc);
boolean isPublicEditable = isPublic && (request.getUserPrincipal() != null);
```

then, below, you will use one or the other of these depending on whether the code is just for **showing values** (`isPublicViewable`) or for **allowing editing** of public data (`isPublicEditable`)

2024-06-11 01:03 UTC, naknomum commented on src/main/webapp/encounters/encounter.jsp
> +            pageContext.setAttribute("editable", (isOwner) && CommonConfiguration.isCatalogEditable(context));
for example, this `pageContext...` line should then use `(isOwner || isPublicEditable)`

2024-06-11 01:04 UTC, naknomum commented on src/main/webapp/encounters/encounter.jsp
> +<% if ((isOwner && CommonConfiguration.isCatalogEditable(context)) || (isPublic && !CommonConfiguration.isCatalogEditable(context))) { %>
this should be returned to original code, except `(isOwner || isPublicEditable)`

2024-06-11 01:05 UTC, naknomum commented on src/main/webapp/encounters/encounter.jsp
>  %>
this clause, since it is only _displaying_ a value, should be `(isOwner || isPublicViewable)`.

2024-06-11 01:06 UTC, naknomum requested changes
some change suggestions regarding viewing versus editing _public data_.
can follow up in discord as needed.

2024-06-20 17:46 UTC, naknomum approved these changes
looks good

2024-06-20 17:46 UTC, merged