Update collaborationInvite.html
WildMeOrg/Wildbook pull request #643
Opened 2024-07-19 16:33 UTC by goddesswarship

**Changes**
- Fixed code formatting
- Removed references to whale sharks and whaleshark.org with giraffes and GiraffeSpotter
- Updated copyright
- Replaced Wild Me company references with Conservation X Labs

2024-07-19 16:35 UTC, goddesswarship commented
@holmbergius Changes made ahead of meeting to fix general GiraffeSpotter bugs.

2024-07-22 18:37 UTC, holmbergius requested changes
Changes requested:

- PNG white text in header for clean readability
- Facebook link to Wild Me
- X link to Wild Me
- Link to donate page is currently just to giraffespotter

2024-07-23 00:01 UTC, goddesswarship commented on src/main/resources/emails/en/collaborationInvite.html
> +                            <img src="https://giraffespotter.org/cust/mantamatcher/img/GS_Spotter07302017_scaled.png" style="-ms-interpolation-mode:bicubic;clear:both;display:block;max-width:100%;out
@holmbergius There's only this and the non-scaled version of this image for the available GiraffeSpotter logos that I've found in the repository so far. Do I need to upload a different non-transparent image to replace it?

2024-07-23 22:40 UTC, goddesswarship commented on src/main/resources/emails/en/collaborationInvite.html
> +                            <img src="https://giraffespotter.org/cust/mantamatcher/img/GS_Spotter07302017_scaled.png" style="-ms-interpolation-mode:bicubic;clear:both;display:block;max-width:100%;out
Nevermind; the issue was with the background color, not the logo image.

2024-07-23 22:45 UTC, goddesswarship commented
Ok, commit 0f2b770b003d484c07990ef5bce3fcacc2fb530d is ready for review.

2024-08-01 20:19 UTC, holmbergius approved these changes
HTML displays cleanly.

2024-08-01 20:19 UTC, merged