Adoption removal
WildMeOrg/Wildbook pull request #791
Opened 2024-09-25 22:30 UTC by naknomum

fixes #283 

:warning: DRAFT

2024-09-27 20:12 UTC, TanyaStere42 commented on src/main/java/org/ecocean/servlet/importer/FixStandardImport.java
can't we just get rid of this?

2024-09-27 20:33 UTC, TanyaStere42 requested changes
one little group of comments I think you can remove. doing a quick addition to adjust some copy, then this should be good to go

2024-09-27 20:56 UTC, TanyaStere42 approved these changes
looks good to me!

2024-09-27 20:57 UTC, merged

2024-09-30 19:06 UTC, goddesswarship commented
👏